name: Build and Deploy Page

on: [push]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run Tests
        run: |
          pip install pytest
          pytest testmain.py

      - name: Create Build Artifact
        if: success()
        run: |
          python main.py > index.html
          mkdir build
          mv index.html build/

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build